[package]
name = "sttt"
version = "0.1.4"
authors = ["Karel Peeters <karel.peeters.leuven@gmail.com>"]
description = "An implemention of super tic tac toe, including bots that play it."
license-file = "NONE.md"
edition = "2018"
default-run = "main"

[dependencies]
rand = { version = "0.7.3", features = ["small_rng"] }
ordered-float = "2.0.0"
regex = "1.1.6"
itertools = "0.9.0"
rayon = "1.3.1"
derive_more = "0.99.9"
static_assertions = "1.1.0"
windows = "0.8.0"

[dev-dependencies]
#criterion = "0.3.3"

[build-dependencies]
windows = "0.8.0"

#[[bench]]
#name = "mcts"
#harness = false

[profile.release]
lto = true
debug = true
