[package]
name = "sttt"
version = "0.1.0"
edition = "2018"

[dependencies]
bit_collection = "0.2.3"
rand = "0.6.5"
rand_xorshift = "0.1.1"
smallvec = "0.6.9"
ordered-float = "1.0.2"

[profile.release]
lto = true