[package]
name = "sttt"
version = "0.1.6"
authors = ["Karel Peeters <karel.peeters.leuven@gmail.com>"]
description = "An implemention of super tic tac toe, including bots that play it."
license-file = "NONE.md"
edition = "2018"
default-run = "main"

[dependencies]
rand = { version = "0.8.3", features = ["small_rng"] }
ordered-float = "2.2.0"
regex = "1.5.3"
itertools = "0.10.0"
rayon = "1.5.0"
derive_more = "0.99.13"
static_assertions = "1.1.0"
windows = "0.9.1"

[build-dependencies]
windows = "0.9.1"

[profile.release]
lto = true
debug = true
