[package]
name = "sttt"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = { version = "0.7.3", features = ["small_rng"] }
smallvec = "0.6.9"
ordered-float = "1.0.2"
lazy_static = "1.3.0"
rand_pcg = "0.1.2"
regex = "1.1.6"

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "mcts"
harness = false

[profile.release]
lto = true
debug = true
